### ISSUE TITLE
BACKEND - Задачи

### ISSUE THREAD

**Issue by danteast** [Andrey-Matanov/cooking_site#4]
1. [x] Клонировать проект
2. [ ] Разработать страницу с рецептом
      Функционал: 
      - просмотр контента;
      - каждый ингредиент сделать кликабельным;
      - автора рецепта сделать кликабельным;
      Требуется разработать:
          - [ ] Создать CRUD Продукты(/products) - добавление, удаление, обновление, отображение-получение. Создать миграцию. Наполнить данными по продуктам. Исполнитель 
          - [ ] Создать CRUD-рецептов(/recipes) добавление рецептов (POST /recipes), редактирование рецептов (PUT /recipes), удаление рецепта (DELETE /recipes/id),  категоризировать рецепты. Создать миграции. Исполнитель - 
          - [ ] Создать CRUD - Категорий рецептов. Создать миграции и настроить связь с рецептами. Исполнитель - 
          - [ ] Создать модель пересчета единиц в граммы. Миграции, настроить связь с продуктами. Исполнитель - 
          - [ ] Создать модель расчета пищевых ценностей рецептов. Исполнитель - 
            
3. [x] Создать базу данных
      Требуется разработать:
      - [x] структуру (выполнено);
      - [x] сделать миграции для таблиц Ingredients, Categories, Recipes; связать их;
      - [x] осуществить seeding для этих таблиц;
Исполнитель -

**Comment by StanislavVNikitin** [comment]
Добавил задачи по функционалу, по контроллерам и моделям.
